SELECT A.CAR_ID, B.CAR_TYPE, FLOOR((B.DAILY_FEE * 30) * ((100 - C.DISCOUNT_RATE) / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
JOIN CAR_RENTAL_COMPANY_CAR AS B
ON A.CAR_ID = B.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C
ON C.DURATION_TYPE = '30일 이상' AND B.CAR_TYPE = C.CAR_TYPE AND C.CAR_TYPE IN ('세단', 'SUV') 
WHERE A.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
)
GROUP BY A.CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, B.CAR_TYPE, A.CAR_ID DESC