-- 자동차 종류 '세단', 'SUV' 
-- 2022년 11년 1월 ~ 2022년 11월 30일 대여가능
-- 대여 금액 50만원 이상 200만원 미만 
-- 자동차 ID, 자동차 종류, 대여 금액 (FEE) 
SELECT A.CAR_ID, B.CAR_TYPE, FLOOR(B.DAILY_FEE * 30 * (100 - C.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
JOIN CAR_RENTAL_COMPANY_CAR AS B
ON A.CAR_ID = B.CAR_ID AND (B.CAR_TYPE = 'SUV' OR B.CAR_TYPE = '세단')
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C
ON B.CAR_TYPE = C.CAR_TYPE
WHERE C.DURATION_TYPE = '30일 이상' AND A.CAR_ID NOT IN (
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
)
GROUP BY CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC