SELECT A.USER_ID, A.NICKNAME, CONCAT(A.CITY, ' ', A.STREET_ADDRESS1, ' ', A.STREET_ADDRESS2) AS 전체주소,
    CONCAT(LEFT(A.TLNO, 3), '-', SUBSTRING(A.TLNO, 4, 4), '-', RIGHT(A.TLNO, 4)) AS 전화번호
FROM USED_GOODS_USER AS A
JOIN USED_GOODS_BOARD AS B
ON A.USER_ID = B.WRITER_ID
GROUP BY A.USER_ID
HAVING COUNT(*) >= 3
ORDER BY USER_ID DESC