# SELECT YEAR(A.SALES_DATE) AS YEAR, MONTH(A.SALES_DATE) AS MONTH, B.GENDER, COUNT(*) AS USERS
# FROM ONLINE_SALE AS A
# JOIN USER_INFO AS B
# ON A.USER_ID = B.USER_ID 
# WHERE GENDER IS NOT NULL
# GROUP BY YEAR, MONTH, GENDER
# ORDER BY YEAR, MONTH, GENDER

SELECT C.YEAR, C.MONTH, C.GENDER, COUNT(*) AS USERS
FROM (
    SELECT DISTINCT YEAR(A.SALES_DATE) AS YEAR, MONTH(A.SALES_DATE) AS MONTH, B.GENDER, A.USER_ID
    FROM ONLINE_SALE AS A
    JOIN USER_INFO AS B
    ON A.USER_ID = B.USER_ID
    WHERE GENDER IS NOT NULL
) AS C
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER
