SET @TOTAL = (
    SELECT COUNT(*)
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
);

SELECT C.YEAR, C.MONTH, COUNT(*) AS PUCHASED_USERS, ROUND(COUNT(*) / @TOTAL, 1) AS PUCHASED_RATIO
FROM (
    SELECT DISTINCT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, A.USER_ID
    FROM ONLINE_SALE AS A
    JOIN USER_INFO AS B
    ON A.USER_ID = B.USER_ID AND YEAR(JOINED) = 2021
) AS C
GROUP BY C.YEAR, C.MONTH
ORDER BY YEAR, MONTH