-- 2021년에 가입한 전체 회원들 중 상품을 구매한 회원 수와 구매한 회원 비율
-- 년, 월 별로 출력 
SELECT YEAR, MONTH, COUNT(*) AS PUCHASED_USERS, ROUND(COUNT(*) / (
    SELECT COUNT(*)
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
), 1) AS PUCHASED_RATIO
FROM (
    SELECT DISTINCT YEAR(A.SALES_DATE) AS YEAR, MONTH(A.SALES_DATE) AS MONTH, A.USER_ID
    FROM ONLINE_SALE AS A
    JOIN USER_INFO AS B
    ON A.USER_ID = B.USER_ID AND YEAR(B.JOINED) = 2021
) AS C
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH 


-- (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021)