SELECT A.YEAR, A.MONTH, COUNT(*) AS PUCHASED_USERS, ROUND(COUNT(*) / (
    SELECT DISTINCT COUNT(USER_ID)
    FROM USER_INFO 
    WHERE YEAR(JOINED) = 2021
), 1) AS PUCHASED_RATIO
FROM (
    SELECT DISTINCT USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
    FROM ONLINE_SALE
) AS A
JOIN USER_INFO AS B
ON A.USER_ID = B.USER_ID
WHERE YEAR(B.JOINED) = 2021
GROUP BY A.YEAR, A.MONTH
ORDER BY YEAR, MONTH 










