SELECT A.HISTORY_ID, CASE
    WHEN C.DURATION_TYPE IS NULL THEN A.DATEDIFF * B.DAILY_FEE
    ELSE FLOOR((A.DATEDIFF * B.DAILY_FEE) * ((100 - C.DISCOUNT_RATE) / 100))
    END AS FEE
FROM (
    SELECT *, DATEDIFF(END_DATE, START_DATE) + 1 AS DATEDIFF, CASE
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 7 THEN NULL
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 30 THEN '7일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 90 THEN '30일 이상'
        ELSE '90일 이상'
        END AS DURATION_TYPE
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
) AS A
JOIN CAR_RENTAL_COMPANY_CAR AS B
ON A.CAR_ID = B.CAR_ID AND B.CAR_TYPE = '트럭'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C
ON B.CAR_TYPE = C.CAR_TYPE AND A.DURATION_TYPE = C.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC