SELECT A.HISTORY_ID, CASE
    WHEN A.DURATION_TYPE IS NULL THEN B.DAILY_FEE * A.DIFF
    ELSE FLOOR((B.DAILY_FEE * A.DIFF) * ((100 - C.DISCOUNT_RATE) / 100))
    END AS FEE
FROM (
    SELECT *, DATEDIFF(END_DATE, START_DATE) + 1 AS DIFF, CASE
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 7 THEN NULL
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 30 THEN '7일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 90 THEN '30일 이상'
        ELSE '90일 이상' 
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
) AS A
JOIN CAR_RENTAL_COMPANY_CAR AS B
ON A.CAR_ID = B.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C
ON A.DURATION_TYPE = C.DURATION_TYPE AND B.CAR_TYPE = C.CAR_TYPE
WHERE B.CAR_TYPE = '트럭'
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC