SELECT C.HISTORY_ID,CASE 
    WHEN C.DURATION_TYPE IS NULL THEN C.DIFF * C.DAILY_FEE
    ELSE FLOOR(C.DIFF * C.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100)
    END AS FEE
FROM (
    SELECT A.HISTORY_ID, A.CAR_ID, B.CAR_TYPE, A.START_DATE, A.END_DATE, DATEDIFF(A.END_DATE, A.START_DATE) + 1 AS DIFF, B.DAILY_FEE, CASE 
        WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 < 7 THEN NULL
        WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 < 30 THEN '7일 이상'
        WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 < 90 THEN '30일 이상'
        ELSE '90일 이상'
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
    JOIN CAR_RENTAL_COMPANY_CAR AS B
    ON A.CAR_ID = B.CAR_ID AND B.CAR_TYPE = '트럭'
) AS C
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
ON C.DURATION_TYPE = D.DURATION_TYPE AND D.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC