SELECT DISTINCT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
FROM DEVELOPERS AS A, (
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
) AS B
WHERE (A.SKILL_CODE & B.CODE) > 0
ORDER BY ID