SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS A
JOIN REST_REVIEW  AS B
ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT COUNT(*) AS COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC
        LIMIT 1
    )
)
ORDER BY REVIEW_DATE, B.REVIEW_TEXT

# SELECT *
# FROM REST_REVIEW AS A
# JOIN MEMBER_PROFILE AS B
# ON A.MEMBER_ID = B.MEMBER_ID
