SELECT A.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_TREE AS A
JOIN ITEM_INFO AS B
ON A.PARENT_ITEM_ID = B.ITEM_ID
JOIN ITEM_INFO AS C
ON A.ITEM_ID = C.ITEM_ID
WHERE B.RARITY LIKE '%RARE%'
ORDER BY ITEM_ID DESC